- hosts: homelab
  become: yes
  vars_files:
    - vars/default.yml

  tasks:
    - name: Setup SSH Public Key authentication
      ansible.posix.authorized_key:
        user: '{{ username }}'
        state: present
        key: "{{ lookup('file', item) }}"
      with_first_found:
        - files:
          - "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
          - "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"

    - name: Allow sudo without password
      community.general.sudoers:
        name: allow-nopassword
        state: present
        user: "{{ username }}"
        nopassword: true
        commands: ALL
