---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Create Jenkins' Dockerfile build directory
      file:
        path: /tmp/jenkins
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy Jenkins Dockerfile
      copy:
        src: ./Dockerfile
        dest: /tmp/jenkins/Dockerfile
        owner: root
        group: root
        mode: '0644'

    - name: Copy Jenkins plugins list
      copy:
        src: ./plugins.txt
        dest: /tmp/jenkins/plugins.txt
        owner: root
        group: root
        mode: '0644'

    - name: Build Jenkins container image
      docker_image:
        name: jenkins-custom:v1.0
        build:
          path: /tmp/jenkins
        source: build
        state: present

    - name: "Create Jenkins config directory"
      file:
        path: /var/jenkins
        state: directory

    - name: Create a Jenkins container
      docker_container:
        name: jenkins
        image: jenkins-custom:v1.0
        recreate: yes
        volumes:
          - "/var/jenkins:/var/jenkins_home"
        restart_policy: unless-stopped
        privileged: true
        user: root
        ports:
          - 50003:50000
        networks:
          - name: traefik
        labels:
          traefik.enable: "true"
          traefik.http.routers.jenkins.rule: Host(`jenkins.tools.thomassen.pro`)
          traefik.http.routers.jenkins.entrypoints: websecure
          traefik.http.routers.jenkins.tls: "true"
          traefik.http.routers.jenkins.tls.certresolver: letsencrypt
          traefik.http.services.jenkins.loadbalancer.server.scheme: http
          traefik.http.services.jenkins.loadbalancer.server.port: "8080"
        env:
          JAVA_OPTS: -Djenkins.install.runSetupWizard=false
          JENKINS_OPTS: '--argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin={{ password }} --argumentsRealm.roles.admin=admin'

    - name: Install Jenkins Pipeline
      get_url:
        url: https://updates.jenkins-ci.org/latest/build-pipeline-plugin.hpi
        dest: /var/jenkins/plugins
