---
- hosts: all
  become: true
  #vars_files:
  #  - vars/default.yml

  tasks:
    - name: "Create .keys directory"
      file:
        path: ~/.keys
        state: directory

    - name: "Copy TransIP private key"
      copy:
        src: ~/.keys/transip
        dest: ~/.keys/transip

    - name: Create a network for Traefik
      docker_network:
        name: traefik

    - name: Create a Traefik container
      docker_container:
        name: traefik
        image: traefik:v2.5
        command:
          - --log.level=DEBUG
          - --entrypoints.web.address=:80
          - --entrypoints.websecure.address=:443
          - --providers.docker
          - --api
          - --api.dashboard=true
          - --certificatesResolvers.letsencrypt.acme.email=nandothomassen@gmail.com
          - --certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
          - --certificatesResolvers.letsencrypt.acme.dnsChallenge=true
          - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=transip
          - --certificatesResolvers.letsencrypt.acme.dnsChallenge.delayBeforeCheck=0
          - --certificatesResolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53
          - --serverstransport.insecureskipverify=true
        restart_policy: unless-stopped
        labels:
          # Request a certificate for the domains thomassen.pro (main) and *.tools.thomassen.pro (SAN)
          traefik.http.routers.traefik.tls: 'true'
          traefik.http.routers.traefik.tls.certresolver: letsencrypt
          traefik.http.routers.traefik.tls.domains[0].main: "thomassen.pro"
          traefik.http.routers.traefik.tls.domains[0].sans: "*.tools.thomassen.pro"
          traefik.http.routers.api.rule: Host(`traefik.tools.thomassen.pro`)
          traefik.http.routers.api.service: api@internal
          traefik.http.routers.traefik.entrypoints: websecure
          traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
          traefik.http.routers.redirs.rule: hostregexp(`{host:.+}`)
          traefik.http.routers.redirs.entrypoints: web
          traefik.http.routers.redirs.middlewares: redirect-to-https
        env:
          TRANSIP_ACCOUNT_NAME: nandothomassen
          TRANSIP_PRIVATE_KEY_PATH: /private.key
        ports:
          - 80:80
          - 443:443
        volumes:
          - "letsencrypt:/letsencrypt/"
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "~/.keys/transip:/private.key:ro"
        networks:
          - name: traefik
